<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net46;net48;net6.0-windows;net8.0-windows</TargetFrameworks>
    <OutputType>Exe</OutputType>
    <UseWindowsForms>false</UseWindowsForms>
    <RootNamespace>DHWifiClient2ConsoleSample</RootNamespace>
    <AssemblyName>DHWifiClient2ConsoleSample</AssemblyName>
    <Platforms>x86;x64</Platforms>
    <Platform Condition="'$(Platform)' == ''">x64</Platform>
    <PlatformTarget>$(Platform)</PlatformTarget>
    <RuntimeIdentifiers>win-x86;win-x64</RuntimeIdentifiers>
    <RuntimeIdentifier Condition="'$(Platform)' == 'x86'">win-x86</RuntimeIdentifier>
    <RuntimeIdentifier Condition="'$(Platform)' == 'x64'">win-x64</RuntimeIdentifier>
    <Prefer32Bit>false</Prefer32Bit>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <Deterministic>true</Deterministic>
    <OutputPath>..\..\output\$(Configuration)\</OutputPath>
    <AppendTargetFrameworkToOutputPath>true</AppendTargetFrameworkToOutputPath>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
  </PropertyGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'net46'">
    <Reference Include="System" />
    <Reference Include="System.Core" />
    <Reference Include="Microsoft.CSharp" />
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'net48'">
    <Reference Include="System" />
    <Reference Include="System.Core" />
    <Reference Include="Microsoft.CSharp" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\lib\DHWifiClient.NET\DHWifiClient.NET.csproj" />
  </ItemGroup>

</Project>
